// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grqgftrusuxqdjxqzjwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdycWdmdHJ1c3V4cWRqeHF6andjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzYxNzksImV4cCI6MjA2Mzk1MjE3OX0.0wsnaoHxaDxH1yjDX2h7a_jOd0M-r-jYhcP2nbIWGaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);